### ISSUE TITLE
Animated meshes

### ISSUE THREAD

**Issue by samuraishamploo** [keijiro/VectorFieldExamples#5]
Hello, 

Have you an idea on how using an animated mesh with your VFX sample ? 

Thank you !

**Comment by keijiro** [comment]
I think it's difficult to animate a vector field because it would spend tons of memory/storage. It's better to approximate by interpolating a few key frames.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
